In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_excel('PJMW_MW_Hourly.xlsx')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143206 entries, 0 to 143205
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   Datetime  143206 non-null  datetime64[ns]
 1   PJMW_MW   143206 non-null  int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 2.2 MB

In [10]:
df.duplicated().sum()

0

In [6]:
df['Datetime'].duplicated().sum()

4

In [17]:
df.isnull().sum()

Datetime    0
PJMW_MW     0
dtype: int64

In [9]:
df[df['Datetime'].duplicated(keep=False)]

                  Datetime  PJMW_MW
104424 2014-11-02 02:00:00     4613
104425 2014-11-02 02:00:00     4571
113208 2015-11-01 02:00:00     3927
113209 2015-11-01 02:00:00     3832
121848 2016-11-06 02:00:00     4114
121849 2016-11-06 02:00:00     4089
130656 2017-11-05 02:00:00     4042
130657 2017-11-05 02:00:00     3984

In [18]:
# Creating a copy 
df_copy1 = df.copy()

In [11]:
df = df.sort_values("Datetime")

In [ ]:
# df['Datetime'] = pd.to_datetime(df['Datetime'])

In [6]:
df.head()

             Datetime  PJMW_MW
0 2002-12-31 01:00:00     5077
1 2002-12-31 02:00:00     4939
2 2002-12-31 03:00:00     4885
3 2002-12-31 04:00:00     4857
4 2002-12-31 05:00:00     4930

In [5]:
print("\nDATASET INFO")
print("Shape:", df.shape)
print("Start:", df.index.min())
print("End:", df.index.max())
print(df.describe())

DATASET INFO
Shape: (143206, 2)
Start: 0
End: 143205
                            Datetime        PJMW_MW
count                         143206  143206.000000
mean   2010-06-02 03:39:50.656816128    5602.375089
min              2002-04-01 01:00:00     487.000000
25%              2006-05-02 03:15:00    4907.000000
50%              2010-06-02 04:30:00    5530.000000
75%              2014-07-03 06:45:00    6252.000000
max              2018-08-03 00:00:00    9594.000000
std                              NaN     979.142872